export const columns = [
	{
		title: 'Id',
		dataIndex: '_id',
		key: '_id',
		ellipsis: true,
		width: '100px',
	},
	{
		title: 'IP',
		dataIndex: 'IP',
		key: 'IP',
		ellipsis: true,
		width: '100px',
	},
	{
		title: 'Computer Name',
		dataIndex: 'computerName',
		key: 'computerName',
		ellipsis: true,
		width: '200px',
	},
	{
		title: 'Verify',
		dataIndex: 'verifySuccess',
		key: 'verifySuccess',
		width: '80px',
	},
	{
		title: 'Register',
		dataIndex: 'registerSuccess',
		key: 'registerSuccess',
		width: '80px',
	},
	{
		title: 'Create Date',
		dataIndex: 'createdDate',
		key: 'createdDate',
		width: '200px',
	},
	{
		title: 'Tag',
		dataIndex: 'tag',
		key: 'tag',
		width: '200px',
	},
	{
		title: 'Elapsed',
		dataIndex: 'elapsed',
		key: 'elapsed',
		width: '100px',
	},
	{
		title: 'Before Register',
		dataIndex: 'beforeRegister',
		key: 'beforeRegister',
		width: '100px',
	},
	{
		title: 'Before Login',
		dataIndex: 'beforeLogin',
		key: 'beforeLogin',
		width: '100px',
	},
	{
		title: 'Before Verify',
		dataIndex: 'beforeVerify',
		key: 'beforeVerify',
		width: '100px',
	},
]
